\l deck
B"-"
C"1010data from Scratch"
B"-"
B" "
B" "
T"Easier said than done!  Here are the puzzle pieces to put together:"
L"Define a structure for data representation: documents, objects, tables, etc"
L"You'll need to cut this up, then schedule compute across a cluster (HDFS vs segs)"
L"Your users are not going to want to deal with that.  Create DSL for processing"
L"Your users are not going to want to deal with THAT.  Write GUI that generates DSL"
B" "
T"gl;hf"
N[d[1]-14]
3:h;
_exit 0
