\l deck
B"-"
C"Scaling"
B"-"
B" "
B" "
T"\"We have implemented [two versions of FFT] ... the relative speed ..."
T"is determined by the communication-to-computation-rates ratio of the"
T"parallel computer on which they are executed."
B" "
T"When the ratio is high, [one] is faster.  Otherwise, [two] is faster.\""
B"  "
T"            Edelman, McCorquodale, Toledo: The Future Fast Fourier Transform? (1997)"
N[d[1]-14]
_exit 0
