\l deck
B"-"
C"Scaling"
B"-"
B" "
B" "
T"Transistor density doubles, on average, every 18 months (Moore's law)."
T"Quantites that depend on transistor density should also double."
B" "
B" "
T"This is great for HPL!"
T"But transferring data down a wire isn't the same."
T"Therefore, different operations scale differently."
B" "
T"Consider the following rates:"
L"vector arithmetic"
L"cache reference"
L"memory IO"
L"disk IO"
L"PCI Bus / Northbridge"
L"network IO"
N[d[1]-22]
3:h;
_exit 0
